version: '3.8'

services:

   # rabbitmq:
   #  image: rabbitmq:3-management
   #  hostname: rabbitmq
   #  container_name: rabbitmq
   #  ports:
   #    - "5672:5672"
   #    - "15672:15672"
 
   # seq:
   #  image: datalust/seq:latest
   #  container_name: seq
   #  hostname: seq
   #  environment:
   #    - ACCEPT_EULA=Y
   #  ports:
   #    - 5341:80

   banking:
    build:
      context: .
      dockerfile: Bankink/Banking.Api/Dockerfile
    container_name: users.api
    restart: on-failure
    ports:
      - "5003:8080"
      - "5004:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_CONNECTION_STRING=Host=${POSTGRE_DB_HOST};Port=${POSTGRE_DB_PORT};Database=${BANKING_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
